project:
  type: website
  resources:
    - google7af2f480fcbc996e.html
    - google586a458f35a0b15b.html
  output-dir: _docs

metadata-files:
  - _website.yml
  - _format.yml
  
execute:
  freeze: auto  
  